### ISSUE TITLE
Wait for connection

### ISSUE THREAD

**Issue by ritiek** [ritiek/net-mpris#3]
If the player isn't already running on the remote machine, one will get this error when starting net-mpris:
```
$ python3 netmpris.py 
netmpris.py:614: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  on_metadata(player, player.get_property('metadata'))
netmpris.py:614: Warning: g_variant_ref_sink: assertion 'value->ref_count > 0' failed
  on_metadata(player, player.get_property('metadata'))
Traceback (most recent call last):
  File "netmpris.py", line 614, in <module>
    on_metadata(player, player.get_property('metadata'))
  File "netmpris.py", line 576, in on_metadata
    mpris_metadata = (metadata['xesam:url'],
TypeError: 'NoneType' object is not subscriptable
```

Instead of this error, it would be a good idea to wait for the player to launch on the remote machine.

**Comment by ritiek** [comment]
Closed by 247c1e5b7139769bfd72f596d1fdf1fbd671749e.
